//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protobuf.proto
namespace protobuf
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Message")]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        public Message() { }

        private Message.MessageType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public Message.MessageType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private Message.Info _info;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Message.Info info
        {
            get { return _info; }
            set { _info = value; }
        }
        private Message.Response _response = Message.Response.OK;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"response", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(Message.Response.OK)]
        public Message.Response response
        {
            get { return _response; }
            set { _response = value; }
        }
        private Message.SemOptions _semOption = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"semOption", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Message.SemOptions semOption
        {
            get { return _semOption; }
            set { _semOption = value; }
        }
        private Message.CheckBlock _checkBlock = null;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"checkBlock", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Message.CheckBlock checkBlock
        {
            get { return _checkBlock; }
            set { _checkBlock = value; }
        }
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Info")]
        public partial class Info : global::ProtoBuf.IExtensible
        {
            public Info() { }

            private int _ipIndex;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ipIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int ipIndex
            {
                get { return _ipIndex; }
                set { _ipIndex = value; }
            }
            private int _client = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"client", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int client
            {
                get { return _client; }
                set { _client = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SemOptions")]
        public partial class SemOptions : global::ProtoBuf.IExtensible
        {
            public SemOptions() { }

            private string _name;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string name
            {
                get { return _name; }
                set { _name = value; }
            }
            private int _value = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int value
            {
                get { return _value; }
                set { _value = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CheckBlock")]
        public partial class CheckBlock : global::ProtoBuf.IExtensible
        {
            public CheckBlock() { }

            private int _initClient;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"initClient", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int initClient
            {
                get { return _initClient; }
                set { _initClient = value; }
            }
            private int _sendingClient;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"sendingClient", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int sendingClient
            {
                get { return _sendingClient; }
                set { _sendingClient = value; }
            }
            private string _targetSem;
            [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"targetSem", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string targetSem
            {
                get { return _targetSem; }
                set { _targetSem = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        [global::ProtoBuf.ProtoContract(Name = @"MessageType")]
        public enum MessageType
        {

            [global::ProtoBuf.ProtoEnum(Name = @"HB", Value = 0)]
            HB = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"SEM_CREATE", Value = 1)]
            SEM_CREATE = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"SEM_DESTROY", Value = 2)]
            SEM_DESTROY = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"SEM_P", Value = 3)]
            SEM_P = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"SEM_V", Value = 4)]
            SEM_V = 4,

            [global::ProtoBuf.ProtoEnum(Name = @"SEM_CHECK", Value = 5)]
            SEM_CHECK = 5,

            [global::ProtoBuf.ProtoEnum(Name = @"CHECK_BLOCK", Value = 6)]
            CHECK_BLOCK = 6
        }

        [global::ProtoBuf.ProtoContract(Name = @"Response")]
        public enum Response
        {

            [global::ProtoBuf.ProtoEnum(Name = @"OK", Value = 0)]
            OK = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"NO", Value = 1)]
            NO = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"ERROR", Value = 2)]
            ERROR = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"ASK", Value = 3)]
            ASK = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}